### ISSUE TITLE
Jenkins keeps running out of Space

### ISSUE THREAD

**Issue by diasdavid** [ipfs/testing#123]
## What is the time sink?

Jenkins keeps running out of Space

## How do you think it can be solved?

Get bigger machine or develop a post CI task that cleans after

## How many hours per week do you waste thanks to this time sink?

Sum of hours per multiple contributor, easily 40 or more.

## How important do you think this is to fix?

It is a big PITA

**Comment by diasdavid** [comment]
everyday https://github.com/ipfs/js-ipfs-api/pull/806#issuecomment-412799656

**Comment by diasdavid** [comment]
Duplicate of https://github.com/ipfs/testing/issues/118, closing

**Comment by alanshaw** [comment]
Coincidentally I was just separately saying to @VictorBjelkholm that any reason that CI fails because of something other than the tests failing is really bad. It’s super frustrating and time consuming for the developer and wastes resources.

Off the top of my head the big issues are:
   * out of disk space errors
   * failed npm module installs
   * random segfaults

It also really sucks when this happens for contributors as they can’t just restart a build. The fact that this effects the community as well as PL is really bad.

**Comment by VictorBjelkholm** [comment]
These are the current open issues for addressing these problems:

- Missing packages in registry
  - https://github.com/ipfs/testing/issues/51 Add a cache layer for npm registry on CI
- Disk space
  - https://github.com/ipfs/testing/issues/120 Monitoring of disk space
  - https://github.com/ipfs/testing/issues/118 Collection of potential causes of disk space problems
- Segfaults
  - https://github.com/ipfs/testing/issues/112
    - Havent found the reason why, switching nodejs version seems to have stopped it from happening
