### ISSUE TITLE
IPFS nodes on master and workers are unable to send data between them

### ISSUE THREAD

**Issue by alanshaw** [ipfs/testing#136]
## Which Project is this about?

ipfs/blog

## Provide a link to a example run where it went wrong

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fblog/detail/PR-171/10/pipeline

## Which platform did the issue happen on?

n/a

**Comment by VictorBjelkholm** [comment]
The issue here is that the go-ipfs nodes running on the master and worker seemingly can't send data in-between them, although they are connected (confirmed via `ipfs swarm peers`) and they can see each others content (confirmed via `ipfs dht findprovs` listing the other node). Even though everything looks correct, when running `ipfs pin add` or `ipfs refs -r`, the nodes are unable to fetch even one block from the other...

Currently they are running a old version of go-ipfs (v0.4.13) so I'm gonna try to upgrade them and see if it makes it better.

Other than that, @ipfs/go-team I'd love to have some ideas on how to debug this to know exactly where the issue is, as I cannot figure out where/what the exact problem is.

**Comment by VictorBjelkholm** [comment]
Pretty sure I found out the reason. All the linux workers are using the same Peer Identity, so Jenkins master thinks it's connected to the right peer (right ID, wrong IP). Can't believe I didn't see this before...
