### ISSUE TITLE
Standarized Makefile for go projects

### ISSUE THREAD

**Issue by diasdavid** [ipfs/testing#47]
Ref: https://github.com/ipfs/community/issues/276

Continue discussion here

**Comment by diasdavid** [comment]
@Stebalien exactly why I moved it to this repo for the DX working group :)

**Comment by Stebalien** [comment]
Oh! Sorry, I thought you were moving issues *there* and leaving these as tombstones.

**Comment by chriscool** [comment]
Copying make targets suggested in https://github.com/ipfs/community/issues/276:

- `make deps` (installs `gx` and dependencies)
- `make install` (runs `make build` and installs resulting binary(ies))
- `make check` (runs `go fmt` and possibly `go vet`)
- `make test` (runs `go test`)
- `make sharness` (runs the sharness tests if available, otherwise exists with 0)
- `make build` (builds a binary if possible, otherwise exists with 0)
